docs/_includes/markup/form-section-header-sentence.njk
docs/_includes/markup/tabbed-content-rounded.njk
docs/_includes/markup/tabbed-content-traditional.njk
docs/_layouts/quick.njk
docs/sample-html/index.md

This PR:
- Updates the Quick Start page to match the file file better

Update quick start file

---

docs/index.njk

This PR:
- Removes the link to home in the logo. This user is already on the home page.
- This link appears nowhere else on the site.

Update Home Page link on Home Page

---

docs/hero-blocks/dual-pane.md

Getting rid of syntax in md file to make "Best Practice" a level 2 header.

Header Fix - Dual Pane

---

docs/index.njk

This PR:
- fixes the button alignment at the bottom of the home page

Update CTA Button at Home Page Bottom

---

scss/_custom.scss

This PR adjusts the box shadow on the content container class.

Content Container Shadow Tweaks

---

docs/_includes/header.njk
docs/_layouts/area-page.njk
docs/_layouts/default.njk

This PR:
- Changes some a11y related items found using automated tests

Updates for automated a11y testing

---

docs/_includes/page-title.njk
docs/_layouts/area-page.njk
docs/_layouts/guide.njk
docs/_layouts/human-sitemap.njk
docs/css/site.css

This PR:
- aligns edges of various layouts better

Adjusted layouts’ adges

---

docs/_includes/markup/documentation-internal.njk
docs/_includes/markup/documentation-public.njk
docs/_includes/markup/item-details-internal.njk
docs/page-templates/404-page-internal.md
docs/page-templates/404-page-public.md
docs/page-templates/documentation-page-internal.md
docs/page-templates/documentation-page-public.md
docs/page-templates/error-page-internal.md
docs/page-templates/error-page-public.md
docs/page-templates/item-details-page-internal.md

This PR restores missing files.

Missing files restored

---

docs/_includes/markup/toggle-tokens-exclusive.njk
docs/_includes/markup/toggle-tokens-inclusive.njk
scss/_custom-forms.scss

This PR:
- Adds disabled states for toggle-tokens

Disabled states for toggle-tokens

---

docs/404.md
docs/_layouts/default-minimal.njk

Replacing basic line of text with the newest 404 Internal template:
Go to the [dashboard](https://pelican-test.ots.la.gov/page-templates/404-page-internal/) for a fresh start.
changes to
Go to the [Get Started](http://get-started/) for a fresh start.
pelican-test.ots.la.govpelican-test.ots.la.gov
[404 Page Internal | Pelican, Louisiana’s Design System](https://pelican-test.ots.la.gov/page-templates/404-page-internal/)
Pelican will provide a scalable, modern base on which to build digital products for Louisiana citizens.
then, for the button:
Go to Get Started and remove the icon

404 - Site style update

---

docs/_layouts/guide.njk
docs/css/site.css

This PR adds CSS rules which limits the width of text on certain layouts.

Adds max-width css rules

---

docs/_includes/markup/hero-boxed-in-photo.njk
docs/_includes/markup/hero-dual-pane.njk
docs/_includes/markup/hero-single-pane.njk
docs/_includes/markup/hero-text-color-toned-photo.njk
docs/_includes/markup/hero-textbox-over-photo.njk

typos in heroes

---

docs/_includes/markup/checkboxes.njk
docs/_includes/markup/input-date-multiple-fields.njk
docs/_includes/markup/input-date-picker.njk
docs/_includes/markup/input-email.njk
docs/_includes/markup/input-file.njk
docs/_includes/markup/input-number.njk
docs/_includes/markup/input-search.njk
docs/_includes/markup/input-tel.njk
docs/_includes/markup/input-text.njk
docs/_includes/markup/input-url.njk
docs/_includes/markup/select.njk
docs/_includes/markup/switches-big.njk
docs/_includes/markup/switches-little.njk
docs/_includes/markup/textarea.njk
docs/form-controls/select.md
docs/form-controls/switches.md
docs/form-controls/toggle-tokens.md

This PR:
- Fixes some spaces
- Fixes typos

fixes typos in form controls

---

docs/page-templates/landing-page-public.md
scss/_feature.scss

This PR:
Fixes some landing page templates style issues

Landing Page Tweaks

---

docs/_layouts/base.njk

Add the generator meta tag with a value of Eleventy to the default layout.

Add 11ty in the generator meta tag

---

docs/components/buttons.md
docs/form-controls/select.md

This PR:
- Adds a dropdown button

Adds dropdown button

---

docs/components/card.md
docs/components/data-tile.md

This PR fixes typos in the Cards and Data Tiles content

cards typos fixed

---

.github/workflows/docs-vnext.yml

* Creates the vNext Workflow for Docs
* Prevents v2 changes from being deployed to Test Site (will require a PR against v2 as well)

vNext Workflow

---

docs/_includes/markup/feature-icons-text.njk
docs/_includes/markup/feature-many-icons.njk
docs/_includes/markup/form-template-address.njk
docs/_includes/markup/form-template-contact.njk
docs/_includes/markup/form-template-name.njk
docs/_includes/markup/form-template-password.njk
docs/_includes/markup/form-template-signin.njk
docs/_includes/markup/form-template-userid.njk
docs/_includes/markup/landing-page.njk
docs/_includes/markup/layout-grid.njk
docs/_includes/markup/official-banner.njk
docs/_includes/markup/pagination.njk
docs/_includes/markup/tabbed-content-rounded.njk
docs/_includes/markup/tabbed-content-traditional.njk
docs/_layouts/area-page.njk
docs/_layouts/human-sitemap.njk
docs/foundation/agency-theming.md
docs/foundation/brand-colors.md
docs/foundation/images.md
docs/foundation/links.md
docs/foundation/spacing.md
docs/foundation/status-colors.md
docs/foundation/ui-colors.md
docs/index.njk
docs/test-page/index.md
scss/_variables-default.scss

Placing back the old spacer values in version 1.0.0 for use in systems that have not converted class uses yet.
mt-3 -> mt-4 (1 rem)
mt-4 -> mt-6 (1.5 rem)
mt-5 -> mt-12 (3 rem)

Spacer Restoration

---

docs/whats-new/index.md
package.json

* Update the version number in `package.json`
* Update release notes

Release 1.1.1 Preparation

---

docs/foundation/images.md

This PR adds a resource about the length of Alt text

Add Alt text length resource

---

scss/_custom.scss
scss/_sidebar.scss
scss/_type.scss

Not entirely sure if all bold text needs an override or not; all text should inherit colors from its parent container.

V2 bug - font weight

---

docs/whats-new/index.md
package.json

- Update version number.
- Update release notes.

Release - v1.1.2

---

docs/foundation/ui-colors.md
scss/_badges.scss
scss/_sidebar.scss
scss/_variables-default.scss

This PR:
- adds two colors present in Pelican 1
- updates MD file for Colors

V2 Adds UI colors for P1 Compatibility

---

scss/_variables-default.scss

This PR restores the padding of the Breadcrumbs component

Breadcrumbs

---

docs/_includes/markup/button-container.njk

This PR adjusts the margin-start for the second group of buttons in the button container

Button Container

---

docs/_includes/markup/alert-danger.njk
docs/_includes/markup/alert-info.njk
docs/_includes/markup/alert-success.njk
docs/_includes/markup/alert-warning.njk
docs/_includes/markup/channels.njk
docs/_includes/markup/checkboxes.njk
docs/_includes/markup/form-password-help.njk
docs/_includes/markup/form-template-userid.njk
docs/_includes/markup/input-file.njk
docs/_includes/markup/modal.njk
docs/_includes/markup/navbar-basic.njk
docs/_includes/markup/navbar-iconic.njk
docs/_includes/markup/navbar-search.njk
docs/_includes/markup/official-banner.njk
docs/_includes/markup/pagination.njk
docs/_includes/markup/popovers.njk
docs/_includes/markup/radios.njk
docs/_includes/markup/select.njk
docs/_includes/markup/switches-little.njk
docs/_includes/markup/tabbed-content-rounded.njk
docs/_includes/markup/tabbed-content-traditional.njk
docs/_includes/markup/toast-danger.njk
docs/_includes/markup/toast-info.njk
docs/_includes/markup/toast-success.njk
docs/_includes/markup/tooltips.njk
docs/components/buttons.md
docs/index.njk
docs/test-page/index.md

Adding on classes in elements that had a visual distinction (without modifying current classes & styles).

Bs5 test - Add Classes

---

docs/_includes/markup/button-back-to-top.njk
scss/_buttons.scss

This PR:
- adjusts markup of the Back to Top button
- adjust SCSS for it

Back to top button

---

docs/_includes/markup/button-add-data.njk
scss/_buttons.scss

This PR
- adjusts markup
- adjusts styling

Add data button

---

docs/_includes/markup/page-title.njk

Page title

---

docs/_includes/markup/official-banner.njk
docs/index.njk
scss/_custom.scss

This PR adjusts markup and SCSS

Official banner

---

docs/_includes/markup/alert-danger.njk
docs/_includes/markup/alert-info.njk
docs/_includes/markup/alert-success.njk
docs/_includes/markup/alert-warning.njk
docs/_includes/markup/modal.njk
docs/_includes/markup/progress-large.njk
docs/_includes/markup/toast-danger.njk
docs/_includes/markup/toast-info.njk
docs/_includes/markup/toast-success.njk
scss/_alert.scss
scss/_toasts.scss

This PR adjust markup and SCSS

Alerts, Modals, Toasts Close Button

---

scss/_feature.scss

Feature blocks

---

docs/_includes/markup/form-password-help.njk
docs/_includes/markup/form-required-message.njk
docs/_includes/markup/form-template-address.njk
docs/_includes/markup/form-template-contact.njk
docs/_includes/markup/form-template-name.njk
docs/_includes/markup/form-template-password.njk
docs/_includes/markup/form-template-signin.njk
docs/_includes/markup/form-template-userid.njk
docs/migration-guide/index.md

Form templates

---

scss/_buttons.scss
scss/_custom.scss

Share social

---

docs/_includes/page-navigation.njk
docs/_layouts/default-internal.njk
docs/_layouts/default-minimal.njk
docs/_layouts/default.njk
scss/_custom.scss
scss/_reboot.scss

Attempting to fix the "double scroll bar" issue by fine-tuning styles and elements in the layout.

App Screen Layout

---

docs/_layouts/default.njk
docs/css/site.css
scss/_custom.scss
scss/_reboot.scss
scss/_sidebar.scss

This PR:
- adjusts SCSS
- adjusts site.css

App screen work

---

docs/index.njk
scss/_custom.scss

This PR:
- adjusts markup classes on the home page
- adjust the SCSS of the Official Banner

Home page tweaks

---

docs/_includes/markup/sample-table.njk
docs/test-page/index.md
scss/_tables.scss
scss/_variables-default.scss

This PR adjust things found on the test page:
- Adjust toasts box shadows
- Adjust table backgrounds
- Adjust sample table markup

Test page work

---

scss/_reboot.scss

This PR adjusts the thickness of the underline under text links

Text decoration link

---

docs/_includes/markup/alert-danger.njk
docs/_includes/markup/alert-info.njk
docs/_includes/markup/alert-success.njk
docs/_includes/markup/alert-warning.njk
docs/_includes/markup/button-container.njk
docs/_includes/markup/component-collapse.njk
docs/_includes/markup/footer-utility.njk
docs/_includes/markup/navbar-basic.njk
docs/_includes/markup/navbar-iconic.njk
docs/_includes/markup/navbar-search.njk
docs/_includes/markup/page-title.njk
docs/_includes/markup/toast-danger.njk
docs/_includes/markup/toast-success.njk
docs/_includes/markup/toast-warning.njk
docs/_layouts/human-sitemap.njk
docs/components/toasts.md

This PR works to sync the appearance of Figma Libraries. Various components are adjusted to match Figma appearance. The is mostly content changes, bits of markup too in the class lists.

Figma / Doc Site Sync

---

docs/components/list-group.md
docs/components/loading-animation.md
docs/components/modal.md
docs/components/navbar.md
docs/components/official-banner.md
docs/components/page-title.md
docs/components/pagination.md
docs/components/popovers-tooltips.md
docs/components/progress.md
docs/components/share-and-social.md
docs/components/sidebar-nav.md
docs/components/skip-link.md
docs/components/tabbed-content.md
docs/components/table.md
docs/components/toasts.md
docs/css/site.css
scss/_buttons.scss
scss/_list-group.scss
scss/pelican.scss

This PR addresses the feedback from the designers meeting

Designers Feedback

---

docs/_includes/markup/hero-single-pane.njk
scss/_hero.scss
scss/_modal.scss
scss/_nav.scss

This PR resolves todo comments in the SCSS.

Resolves Todos

---

docs/_includes/header.njk
docs/_includes/markup/app-screen.njk
docs/_includes/markup/sidebar-nav.njk
docs/_includes/sidebar.njk
docs/components/app-screen.md
docs/js/default.js
docs/migration-guide/index.md
scss/_sidebar.scss

This PR affects the sidebar’s exposure to assistive technology.

Sidebar hide

---

build/.eleventy.js
docs/_includes/markup/documentation-internal.njk
docs/_includes/markup/documentation-public.njk
docs/_includes/markup/sample-toc.njk
docs/_includes/page-contents.njk

Solving problems discovered in bs5 testing:
Removal of nav inside of nav
Addition of an ID on a heading element
The aria-labelledby=“headingID” on the nav element
Do this for all of the On this page items in the site, including sample pages

Bs5 test - toc

---

scss/_custom-forms.scss

This PR embeds a SVG in SCSS rather than call it as a file.

Embed SVG in SCSS

---

docs/_includes/markup/official-banner.njk

Updating documentation of component page to match usage of banner on homepage.

V2 - Official Banner w/h A11y

---

docs/index.njk

This PR:
- adds landmarks
- adds aria roles
- makes screen reader optimizations

V2 a11y home

---

docs/_includes/breadcrumbs.njk
docs/_includes/page-navigation.njk
docs/_layouts/guide.njk

This PR:
- Adds a region to the Guide layout for the content
- Adds optimizations to page navigation

V2 layouts guide

---

docs/_includes/markup/badges.njk
docs/components/badges.md

This PR adds icons to the badges as an option. This is added to help differentiate badge meanings by double encoding.

Updates badges

---

docs/_includes/markup/page-title.njk
docs/components/page-title.md
docs/migration-guide/index.md
scss/_custom.scss

This PR adds Badges to a Page Title. This request comes from the design team to incorporate additional identification helpers in a project.

Badge styles addition for Page Title

---

docs/form-controls/form-section-header.md
docs/migration-guide/index.md

This PR adds a required fields advisory to the Form Section Header. Design team members requested this based upon project needs.

Adjusts form section header

---

scss/_variables-default.scss

This PR changes the gray used for text

V2 text adjust

---

scss/_focus.scss

This PR updates the focus style of the expander button in the Official Banner to be similar to other interactive items’ focus styles

Official Banner Focus Style

---

build/.eleventy.js
docs/_includes/markup/documentation-internal.njk
docs/_includes/markup/documentation-public.njk
docs/_includes/markup/sample-toc.njk
docs/_includes/page-contents.njk
package-lock.json

Solving problems discovered in bs5 testing:
- Removal of nav inside of nav
- Addition of an ID on a heading element
- The aria-labelledby=“headingID” on the nav element
- Do this for all of the On this page items in the site, including sample pages

TOC updates

---

docs/components/page-title.md

This PR adds usage notes about the heading tags in the Page Title component

Update Page-title Content

---

docs/form-controls/checkboxes.md
docs/form-controls/form-section-header.md
docs/form-controls/inputs.md

This PR corrects typos and rewords some sentences for clarity

Typos and clarity

---

docs/accessibility/accessibility-statement.md
docs/accessibility/checklist.md
docs/accessibility/color-contrast.md
docs/accessibility/dyslexia-friendly.md

This PR corrects typos and rewords a few sentences for clarity.

Typos fixed, clarity

---

docs/introduction/considerations.md

This PR corrects a broken link

V2 intro area typos

---

docs/components/back-to-top-button.md
docs/components/button-container.md
docs/components/buttons.md
docs/components/content_container.md
docs/components/dividers.md
docs/components/page-title.md

This PR corrects typos and rewords some sentences for clarity.

V2 components

---

docs/_includes/markup/page-title.njk
docs/components/page-title.md

This PR fixes a typo on the Page Title component sample in documentation.

Heading Fix

---

docs/_includes/markup/404-internal.njk
docs/_includes/markup/404-public.njk
docs/_includes/markup/documentation-public.njk
docs/_includes/markup/error-internal.njk
docs/_includes/markup/error-public.njk
docs/_includes/markup/item-details-internal.njk
docs/_includes/markup/landing-page.njk
docs/page-templates/404-page.md
docs/page-templates/documentation-page.md
docs/page-templates/error-page.md
docs/page-templates/item-details-page.md
docs/page-templates/landing-page.md

This PR:
- Adjusts heading levels
- Uses styles classes to preserve appearance rather than rely on semantic classes

V2 Page Template Heading Fixes

---

docs/_includes/markup/form-template-address.njk
docs/_includes/markup/form-template-contact.njk
docs/_includes/markup/form-template-name.njk
docs/_includes/markup/form-template-password.njk
docs/_includes/markup/form-template-signin.njk
docs/_includes/markup/form-template-userid.njk
docs/form-templates/address.md
docs/form-templates/change-password.md
docs/form-templates/contact-information.md
docs/form-templates/create-user-id-and-password.md
docs/form-templates/name.md
docs/form-templates/sign-in.md
scss/_custom.scss

This PR introduces a style class for form templates. This allows the heading level to change if necessary while preserving appearance.

Creates a style class rather than semantic class

---

docs/components/app-screen.md

This PR fixes a typo in the topbar example which causes a bug.

V2 Topbar Bug Fix

---

docs/components/app-screen.md

This PR fixes a typo in the topbar example which causes a bug.

V1 Topbar Bug Fix 

---

docs/_includes/markup/modal.njk

This PR fixes a heading level issue for the modal title in V1.

V1 Modal Title Fix

---

scss/_custom.scss

This PR removes the bottom border from the Official Banner component.

V2 Tweak Official Banner: Remove bottom border

---

scss/_badges.scss

This PR improves the legibility in badges by:
1. Changing font weight to normal from bold
2. Adjusting letter spacing to .12

V2 Tweak Badges: Improve Legibility

---

docs/migration-guide/index.md
docs/whats-new/index.md

This PR:
- updates the What’s New page to describe the Pelican 2 release
- updates the What’s New page to sync the Figma library with the doc site text
- Adds links to the Migration page to ease navigation

Content Updates for P2 Release

---

docs/js/default.js
package-lock.json
package.json

- Updates the package to beta.7 in perparation for an NPM release.
- Fixes critical audit findings on npm.

Update Package Versions

---

docs/css/site.css
package-lock.json
scss/_breadcrumb.scss

This PR fixes a padding bug which occurs on small viewport sizes.

Fixes padding bug on small viewports

---

docs/form-controls/form-section-header.md

This PR fixes a broken link. It fixes a link found in Form Section Header to Content Container

Fix Broken Link

---

package-lock.json
package.json

* Updates package versions and removes outstanding audit issues on the packages.

[v1] Package Updates

---

docs/_includes/header.njk
package-lock.json
package.json

* Updates package versions and removes outstanding audit issues on the packages.
* Updates the version switcher to default to v2 on the v2 branch.

[v2] Updating Package Versions

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/docs-production.yml
.github/workflows/docs-sandbox.yml
.github/workflows/docs-vnext.yml
.github/workflows/label-maker.yml
.github/workflows/release.yml

Update workflows to the latest versions of their respective actions.

[v1] Update Workflows

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/docs-production.yml
.github/workflows/docs-sandbox.yml
.github/workflows/docs-vnext.yml
.github/workflows/label-maker.yml
.github/workflows/release.yml

Update workflows to the latest versions of their respective actions.

[v2] Workflow Updates

---

docs/index.njk

This PR makes the link more visible by:
- Making it bolder
- enforcing the double-underline on hover

Version Update Banner

---

docs/_includes/header.njk
docs/index.njk
scss/_custom.scss

This PR:
- Creates a message on the home page to indicate that Pelican 1 is user’s current location
- Adds a link in the message for navigating to Pelican 2
- Creates a dropdown button to enable users to switch between docs versions
- Adds necessary SCSS

V1 Version Switcher

---

docs/index.njk

This PR changes the background class of the Get Started section to increase contrast with the button on focus state.

V2 Get Started Banner

---

docs/_includes/markup/form-password-help.njk
docs/_includes/markup/form-template-userid.njk
package-lock.json
scss/_default-theme.scss

This PR 
- adjusts the background color of form inputs
- adjusts the border width of toasts

V2 Forms, Toasts

---

scss/_nav.scss

This PR adjusts the tab border color to be consistent.
Old
New

V2 Update tab border color

---

docs/_includes/markup/app-screen.njk
docs/components/app-screen.md

This PR changes:
- Occurrences of `font-weight-bold` to `fw-bold` to align with the change from Bootstrap 4 to 5

App Screen Class Name

---

docs/_includes/header.njk
docs/accessibility/forms.md
docs/index.njk
package-lock.json
package.json
scss/_buttons.scss
scss/_default-theme-variables.scss
scss/_progress.scss
scss/_reboot.scss
scss/_sidebar.scss

This PR:
- adds omitted CSS variables for theming
- adjusts SCSS where necessary
- changes class on an element in HTML where necessary to accommodate CSS variables
- fixes two typos: in a MD file, and in a CSS variable

Theming for V2 CSS Variables

---

scss/_default-theme-variables.scss
scss/_reboot.scss

This PR removes the customization for text selection. These styles will be delegated to browser control.

Removed text selection styles

---

docs/_includes/color-warning.njk
docs/accessibility/accessibility-statement.md
docs/accessibility/checklist.md
docs/accessibility/color-contrast.md
docs/accessibility/dyslexia-friendly.md
docs/accessibility/headings.md
docs/accessibility/skip-link.md
docs/form-controls/checkboxes.md
docs/form-controls/inputs.md
docs/form-controls/radios.md
docs/form-controls/select.md
docs/form-controls/switches.md
docs/form-controls/textarea.md
docs/form-controls/toggle-tokens.md
docs/form-controls/using-form-controls.md
docs/foundation/agency-theming.md
docs/foundation/icons.md
docs/foundation/links.md
docs/foundation/specific-images.md
docs/foundation/status-colors.md
docs/foundation/typography.md
docs/foundation/ui-colors.md
docs/resources/index.md

This PR addresses the following :
- Corrects typos in text
- Updates WCAG links from 2.1 to 2.2
- Changes text for clarity, such “more accessible” to “WCAG 2.2 compliant”
- Adds an external tool reference in Color Contrast
- Adds an external resource reference in Dyslexia Friendly
- Adds extra information and guidance in Headings, Typography
- Adds specific information in Skip Link
- Rewrites much of Agency Theming to connect better to the Pelican 2 Themer Tool
- Adds specificity in text in Icons and Links pages
- Removes unhelpful text in the alt text of the Specific Images page
- Edits some information in UI Colors

Presents theme guidance, with a11y considerations

---

package-lock.json
package.json

Updating package dependencies.

Updating NPM Packages

---

docs/migration-guide/index.md

This PR introduces extra instructions about updating Javascript and information about Bootstrap 5 removing jQuery as a dependency.

Add Clarity to Migration Guide

---

docs/_includes/markup/button-container.njk
docs/whats-new/index.md
package-lock.json
package.json
scss/_buttons.scss

This PR fixes the following CSS Bugs:
- Fixes color bugs in the Add Data button
- Fixes padding bugs in the Button Container

Fixes CSS Bugs

---

docs/components/cards.md

This PR updates documentation to components. This includes:
- Cards
-

Update Component Documentation

---

docs/_includes/markup/footer-utility.njk
docs/index.njk
docs/whats-new/index.md
package-lock.json
package.json
scss/_buttons.scss
scss/_default-theme.scss

This PR adds shadows to basic buttons.

Basic Button Shadows

---

docs/_includes/markup/official-banner.njk

- Update state seal on official banner

Update Official Banner

---

docs/_includes/markup/page-title.njk
docs/components/badges.md
docs/components/page-title.md
package-lock.json
package.json
scss/_badge-chip.scss
scss/_page-title.scss

This PR changes:
- Updates badge SCSS/CSS for dim variants
- Updates page title SCSS/CSS to incorporate dim badge flexibility
- Updates badge documentation
- Updates page title documentation
- Updates package.json

Badge CSS and Documentation Update

---

docs/foundation/brand-colors.md

This PR fixes:
- Brand color Secondary, darker hex code in the docs

Fixed hex code for secondary darker

---

docs/form-controls/form-section-header.md
docs/whats-new/index.md
package-lock.json
package.json
scss/_forms.scss

This PR:
- Fixes a `.form-section-header` issue
- Adds CSS
- Updates documentations

Fix form section header

---

docs/accessibility/checklist.md
docs/introduction/considerations.md
docs/resources/index.md

This PR updates links which:
- have been changed at their source
- adds some in other places to address automated testing

Updated links
