docs/foundation/typography.md
The Foundation > Typography page has a missing section header, Resources, that is inside of the last HTML rendering.
This has been separated in the md file as other pages have it.
=> Typography - page revision

README.md
There was an old link in the documentation to the aws test site. Fixed to the production documentation site https://pelican.ots.la.gov
=> Update README Documentation Link

.github/workflows/docs-sandbox.yml
Attempting to remove the dependabot PRs from being deployed to Sandbox whenever they are opened. This changes the trigger from being a PR opened against the `main` branch to trigger on any PR as long as it is not coming from dependabot.
=> Remove dependabot from sandbox deployments

docs/_includes/markup/spinner.njk
Placing correct class onto markup file for Bootstrap version 4.
=> Bug - Spinner component w/h visual text

docs/whats-new/index.md, package.json
- Fixes margin and padding across the design system, reducing package size. [92b1c11](https://github.com/la-ots/pelican/commit/92b1c11)
- Add styles from Design System Site back into Pelican [7ce681c](https://github.com/la-ots/pelican/commit/7ce681c)
- Fixes an issue with disabled toggles [f57d2e8](https://github.com/la-ots/pelican/commit/f57d2e8)
- Fixed a padding issue with previous/next buttons [3d594f7](https://github.com/la-ots/pelican/commit/3d594f7)
- Renamed previous/forward buttons to previous/next [789ead8](https://github.com/la-ots/pelican/commit/789ead8)
- Adds disabled state for toggle-tokens [d200ae7](https://github.com/la-ots/pelican/commit/d200ae7)
- Overriding hover state on sidebar buttons [0cf784d](https://github.com/la-ots/pelican/commit/0cf784d)
- Documentation fixes …
=> Update for 1.1.0 Release

docs/css/site.css, scss/_custom.scss
Removing underlines from links in text is a bad idea. However, if the links are presented in a list of links (understood to be a list of links), don’t need underlines. In this case it’s ok to remove them, to reduce visual artefacts. To this end, this PR:
- ensures that Resources links don’t have underlines
=> Underlines in Link

docs/_includes/markup/table.njk
A dark line sit below the header row; this will remove that visual glitch from the top positioning given to the table caption.
=> V2 bug - table caption

docs/_includes/markup/breadcrumbs.njk
Accounting for icons near hidden text, only the hidden element should account for any extra spacing needed.
=> V2 bug - breadcrumb spacing

package-lock.json, scss/_variables-agency.scss
In order to utilize any of the color pallets outside the stylesheets, Pelican will provide class equivalents to properties commonly set using similar naming schema to Bootstrap. These are the properties to be accommodated:
- background color / "bg-___"
- color / "text-___"
=> V2 update - color classes expansion

docs/css/site.css
This PR:
- limits paragraph line lengths in the `content-area` to 80 characters maximum
- adjust spacing between list items in the `content-area` for readability
=> Line lengths, list items

scss/_reboot.scss
This PR removes the icon which appears on links to external sites, when `target="_blank"` is set
=> External link icon

docs/_layouts/default.njk
This PR removes a redundant attribute and value from a semantic element. A `<main>` doesn’t need `role="main"`.
=> Main, Role

docs/index.njk
This PR removes an empty `id=""` which is flagged by the W3C Validator
=> Home hero id error

docs/_includes/markup/buttons-previous-next-page.njk, docs/_includes/markup/page-title.njk, docs/components/buttons-previous-next-page.md, docs/components/page-title.md
This PR:
- adds `aria-label` to the Previous and Next Page buttons
- adds documentation for customizing the aria-label
=> Adds arial-label to Prev Next buttons

docs/_includes/markup/page-title.njk, docs/components/page-title.md
This PR fixes a typo on the Page Title component sample in documentation.
=> V2 Heading Fix

docs/_includes/markup/navbar-basic.njk, docs/_includes/markup/navbar-iconic.njk, docs/_includes/markup/navbar-minimal.njk, docs/_includes/markup/navbar-search.njk
This PR changes the `container-fluid` in the Navbars to just `container` for better alignment with other page blocks.
=> V2 Tweak Navbars: Changes container-fluid to container

docs/_includes/header.njk, docs/index.njk, scss/_sidebar.scss
This PR:
- Creates a message on the home page to indicate that Pelican 2 is the default, canonical version for the docs
- Adds a link in the message for navigating to Pelican 1
- Creates a dropdown button to enable users to switch between docs versions
- Adds necessary SCSS / CSS Variables
=> V2 Version Switcher

package-lock.json, scss/_breadcrumb.scss, scss/_buttons.scss, scss/_card.scss, scss/_nav.scss, scss/_reboot.scss, scss/_sidebar.scss
This PR:
- adds underlines upon hover to many buttons to indicate hover status
- adds double underline style upon hover to links in text to indicate hover status
This needs to be done because our styles currently rely on subtle color changes right now and this is not good practice.
This video presents a before and after : https://share.cleanshot.com/wbpNdPq8
=> [v2] Adds Underlines and double underlines

scss/_default-theme-variables.scss, scss/_default-theme.scss
This PR adjusts cards’ borders to be slightly thinner. This allows more important borders such as form fields to get a little more visual attention.
=> Card Borders Adjusted

docs/accessibility/color-contrast.md
The PR updates the guidance on the Color Contrast page, in the best practices section.
=> Color Contrast Best Practices

docs/foundation/status-colors.md
This PR changes the incorrect documentation of the `info-darker` color. Corrects it to `#004ba1` from `#94080a`.
=> Update Info Darker Hex Value

scss/_official-banner.scss
This PR removes the translucency from the icon on the expander button.
Old
New
=> V2 Update Official Banner

scss/_default-theme-variables.scss, scss/_tables.scss
This PR returns table striping and border thickness to pre 5.3 import.
Old
New
=> V2 Table Stripes

scss/_default-theme-variables.scss, scss/_list-group.scss
This PR adjusts list group background colors to pre BS5.3
Old
New
=> V2 List Group Background Color

docs/_layouts/area-page.njk, docs/css/site.css
This PR applies a slight visual design refactor to the cards on the area page.
The cards have a faint arrow to the right of the link text. When hovered, the icon gets an underline which doesn’t fit well with the icons’ visual design. This refactor positions the icons to the left of the link text and in a way to exclude them from the underline upon hover.
Old
New
=> V2 Area Page Tweaks

docs/_includes/markup/pagination.njk
This PR resolves a contradictory use of accessibility techniques between Display styles and ARIA attributes.
- Changes `d-none` to `visually-hidden`
- Removes `aria-hidden='false'`
=> Pagination Accessibility

docs/index.njk
This PR adds a link to the Figma library at Figma Community Nav on the home page nav.
=> Add Figma Link

docs/_includes/markup/table.njk, docs/whats-new/index.md, scss/_buttons.scss, scss/_reboot.scss
This PR improves accessibility by:
- Putting underlines on links in tables
- Changing underlines to double underlines on hover to links in tables
- Adding a border change to the sidebar button on hover
=> Adds Link and Hover Styles

docs/components/list-group.md, docs/whats-new/index.md, package-lock.json, package.json, scss/_list-group.scss
This PR adjusts the vertical position of the icons in the links of List Groups. This makes the icons vertically-centered. It closes #545
=> Vertical Centers for List Group Link Icons

docs/_includes/markup/app-screen.njk, docs/components/list-group.md, docs/css/your-theme.css, docs/whats-new/index.md, package-lock.json, package.json, scss/_buttons.scss, scss/_custom-forms.scss, scss/_default-theme-variables.scss, scss/_feature.scss, scss/_focus.scss, scss/_form-check.scss, scss/_list-group.scss, scss/_nav.scss, scss/_pagination.scss, scss/_tables.scss, scss/_toc.scss, scss/pelican.scss
This PR does the following:
- Add an omitted CSS variable for Pagination
- Add an omitted CSS variable for Languages Feature Block
- Add an omitted CSS variable for Checkbox and Radios active color
- Fix bug of errant class name preventing theming in Topbar
- Fix bug of incorrect CSS variable used in disabled Toggle Tokens
- Fix bug of links in Tables not inheriting color
- Reformatted dates and headers in What’s New to be easier to scan
=> V2 CSS Variable Additions

docs/_includes/markup/app-screen.njk, docs/components/app-screen.md
This PR does the following:
- Corrects the "aria-haspop" attribute to "aria-haspopup" on the sidebar-button in the topbar of the App Screen component.
=> Update Topbar Aria Attributes

docs/whats-new/index.md, package-lock.json, package.json, scss/_buttons.scss
This PR fixes a bug which causes some `<a>` elements with `btn` class to vertically misalign with other elements of the same class.
=> Fix Button Misalignment

docs/_includes/markup/pagination.njk, docs/_includes/markup/select.njk, docs/_includes/markup/table.njk, docs/_layouts/area-page.njk, docs/components/list-group.md
This PR: 
- removes empty `class` attributes on some markup
- removes empty `aria-label` on some markup
- reduces word count of some screen reader available text
- improves the area page by enabling more content to show at larger screen sizes
- removes erroneous `aria` attributes from the list group with links
=> Fix Markup Typos

docs/_includes/markup/table-scrollable.njk, docs/_includes/markup/table-striped.njk
This PR:
- Changes `<a>` elements into `<button>` elements for the table sorting controls
- this improves the accessibility of the table sorting controls by using elements which are more semantically appropriate
=> Changed Table Sort Buttons
